language: R
sudo: required
cache: packages

after_success:
    - Rscript -e 'covr::codecov()'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - mkdir ~/.R && echo "CXX=g++-4.9" > ~/.R/Makevars
  - sudo apt-get install gfortran
