---
title: "Yeast orphan analysis"
author: "Zebulun Arendsee"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Yeast orphan analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE, message=FALSE}
# document()
library(rmonad)
library(ggplot2)
library(knitr)
library(dplyr)
con <- config()
# file.symlink("../inst/yeast", "INPUT")
# d <- run_fagin(con)
```

```{r, echo=FALSE}
# missues(d) %>% kable(format='html') %>% write('ARCHIVE/issues.html')
# mtabulate(d, code=TRUE) %>% kable(format='html') %>% write('ARCHIVE/table.html')
# es <- as.list(d)[sapply(d, function(x) x$has_error())]
# ws <- as.list(d)[sapply(d, function(x) x$has_warnings())]
```

```{r, echo=FALSE}
invertSummaries <- function(x){
  xs <- list(
    gff         = list(),
    dna         = list(),
    aa          = list(),
    trans       = list(),
    orfgff      = list(),
    orffaa      = list(),
    transorfgff = list(),
    transorffaa = list(),
    nstring     = list()
  )
  for(s in names(x@species)){
    xs$gff         = append(xs$gff         , x@species[[s]]@summaries@gff.summary         )
    xs$dna         = append(xs$dna         , x@species[[s]]@summaries@dna.summary         )
    xs$aa          = append(xs$aa          , x@species[[s]]@summaries@aa.summary          )
    xs$trans       = append(xs$trans       , x@species[[s]]@summaries@trans.summary       )
    xs$orfgff      = append(xs$orfgff      , x@species[[s]]@summaries@orfgff.summary      )
    xs$orffaa      = append(xs$orffaa      , x@species[[s]]@summaries@orffaa.summary      )
    xs$transorfgff = append(xs$transorfgff , x@species[[s]]@summaries@transorfgff.summary )
    xs$transorffaa = append(xs$transorffaa , x@species[[s]]@summaries@transorffaa.summary )
    xs$nstring     = append(xs$nstring     , x@species[[s]]@summaries@nstring.summary     )
  }
  lapply(xs, function(xx) { names(xx) <- names(x@species); xx } )
}
```

```{r, echo=FALSE}
load('ARCHIVE/d1.Rda')
ss <- invertSummaries(d1)
```

```{r, echo=FALSE}
load('ARCHIVE/d2.Rda')

number_of_chromosomes <- function(x){
    lapply(x$dna, function(s) nrow(s@table))
}

initial_protein_residue_counts <- function(x){
    lapply(x$aa, function(s) s@initial_residue)
}

final_protein_residue_counts <- function(x){
    lapply(x$aa, function(s) s@final_residue)
}

protein_has_internal_stop <- function(x){
    lapply(x$aa, function(s) s@has_internal_stop %>% sum)
}

genomic_composition <- function(x){
    x$dna %>% lapply(function(s) s@comp %>% colSums %>% { . / sum(.) })
}
```

```{r, fig.width=8, fig.height=6, echo=FALSE, message=FALSE}
require(ape)
plot(d1@tree)
speciesOrder <- d1@tree$tip.label
```

```{r, echo=FALSE, result='asis'}
nscaf <- number_of_chromosomes(ss)
initialRes <- initial_protein_residue_counts(ss)
finalRes <- final_protein_residue_counts(ss)
hasStop <- protein_has_internal_stop(ss)
genComp <- genomic_composition(ss)

data.frame(
    species = names(nscaf) %>% factor(levels=speciesOrder)
  , n_scaffolds = nscaf %>% unlist %>% unname
  , n_bases = sapply(ss$dna, function(x) x@table$length %>% sum)
  , n_prot = sapply(initialRes, sum) %>% unname
  , GC = sapply(genComp, function(x) ((x['G'] + x['C']) * 100) %>% round)
  , n_oddstart = sapply(initialRes, function(x) { sum(x) - x['M'] }) %>% unname
  , n_oddstop = sapply(finalRes, function(x) { sum(x) - x['*'] }) %>% unname
  , p_N = sapply(genComp, function(x) x['N'] %>% signif(3))
  , n_stop = hasStop %>% unlist %>% unname
) %>%
    dplyr::arrange(species) %>%
    knitr::kable()
```

```{r, echo=FALSE}
# load the binary feature table
load('ARCHIVE/d3.Rda')
```

```{r, echo=FALSE}

plotSecondaryLabels <- function(con, fill='secondary'){
     desc <- data.frame(
        desc = c(
            "known gene"                         , #O1
            "unknown ORF on known mRNA"          , #O2
            "unknown ORF off known mRNA"         , #O3
            "maps off the scaffold"              , #U1
            "possible indel"                     , #U2
            "possible N-string"                  , #U3
            "syntenically scrambled"             , #U5
            "seriously unknown"                  , #U6
            "skipped for technical reasons"      , #U7
            "DNA match to CDS"                   , #N1
            "DNA match to exon"                  , #N2
            "DNA match to mRNA"                  , #N3
            "No DNA match to any known gene"       #N4
        ),
        secondary = c(
            "O1" ,
            "O2" ,
            "O3" ,
            "U1" ,
            "U2" ,
            "U3" ,
            "U5" ,
            "U6" ,
            "U7" ,
            "N1" ,
            "N2" ,
            "N3" ,
            "N4"  
        )
     )
    load(file.path(con@archive, 'd4.Rda'))
    dat <- d4$labels %>%
            lapply(
                function(x) {
                    dplyr::group_by(x[-1], primary, secondary) %>% dplyr::count()
                }
            ) %>%
            dplyr::bind_rows(.id='species') %>%
            {
                .$species <- factor(.$species, levels=speciesOrder)
                . <- merge(., desc)
                .$desc <- paste(.$secondary, .$desc, sep=': ')
                .
            }
    if(fill == 'secondary'){
        ggplot(dat) +
            geom_bar(aes(x=species, y=n, fill=desc), position="dodge", stat="identity") +
            scale_fill_brewer(palette="Set1") +
            theme(
                axis.text.x = element_text(angle=315, hjust=0, vjust=1)
              , legend.position = 'bottom'
            )
    } else {
        ggplot(dat) +
            scale_fill_brewer(palette="Paired") +
            geom_bar(aes(x=desc, y=n, fill=species), position="dodge", stat="identity")+
            theme(
                axis.text.x = element_text(angle=315, hjust=0, vjust=1)
            )
    }
}

```

```{r, fig.width=8, fig.height=6, echo=FALSE}
plotSecondaryLabels(con)
```

```{r, fig.width=8, fig.height=4, echo=FALSE}
plotSecondaryLabels(con, fill='species')
```

```{r, echo=FALSE}
load('ARCHIVE/d5.Rda')
d5$classSum
```

```{r, echo=FALSE}
load('ARCHIVE/final_obj.Rda')
```

```{r, echo=FALSE, result='asis'}
data.frame(
    min    = sapply(d1@synmaps, function(x) x@synmap.summary@width@min)
  , q25    = sapply(d1@synmaps, function(x) x@synmap.summary@width@q25)
  , median = sapply(d1@synmaps, function(x) x@synmap.summary@width@median)
  , q75    = sapply(d1@synmaps, function(x) x@synmap.summary@width@q75)
  , max    = sapply(d1@synmaps, function(x) x@synmap.summary@width@max)
  , mean   = sapply(d1@synmaps, function(x) x@synmap.summary@width@mean)
  , sd     = sapply(d1@synmaps, function(x) x@synmap.summary@width@sd)
  , n      = sapply(d1@synmaps, function(x) x@synmap.summary@width@n)
) %>% knitr::kable(caption="Summary of synteny map widths")
```
